# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [15]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [16]:
import torch

tensor_2 = torch.rand(7, 7)
tensor_2


tensor([[0.4196, 0.3728, 0.3769, 0.0108, 0.9455, 0.7661, 0.2634],
        [0.1880, 0.5174, 0.7849, 0.1412, 0.3112, 0.7091, 0.1775],
        [0.4443, 0.1230, 0.9638, 0.7695, 0.0378, 0.2239, 0.6772],
        [0.5274, 0.6325, 0.0910, 0.2323, 0.7269, 0.1187, 0.3951],
        [0.7199, 0.7595, 0.5311, 0.6449, 0.7224, 0.4416, 0.3634],
        [0.8818, 0.9874, 0.7316, 0.2814, 0.0651, 0.0065, 0.5035],
        [0.3082, 0.3742, 0.4297, 0.9729, 0.9739, 0.4533, 0.3499]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [17]:
tensor_3 = torch.rand(1, 7)
output_3 = torch.matmul(tensor_2, tensor_3.T)
output_3



tensor([[1.6075],
        [0.9380],
        [1.2459],
        [1.7176],
        [2.2199],
        [1.5754],
        [2.1938]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [18]:
torch.manual_seed(0)

tensor_4a = torch.rand(7, 7)
tensor_4b = torch.rand(1, 7)
output_4 = torch.matmul(tensor_4a, tensor_4b.T)

output_4, output_4.shape





(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [19]:
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_6a = torch.rand(2, 3).to(device)
tensor_6b = torch.rand(2, 3).to(device)

print("Device:", device)
tensor_6a, tensor_6b



Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
output_7 = torch.matmul(tensor_6a, tensor_6b.T)
output_7, output_7.shape





(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [22]:
max_8 = output_7.max()
min_8 = output_7.min()

max_8, min_8


(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [23]:
max_index_9 = torch.argmax(output_7)
min_index_9 = torch.argmin(output_7)

max_index_9, min_index_9

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
torch.manual_seed(7)

tensor_10 = torch.rand(1, 1, 1, 10)
tensor_10_squeezed = tensor_10.squeeze()

print(tensor_10, tensor_10.shape)
print(tensor_10_squeezed, tensor_10_squeezed.shape)



tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
